export const WORKSTATIONS_FIELDS_NAME = {
  NAME: "Tên trạm",
  CODE: "",
  SHORT_NAME: "Tên viết tắt",
  SYMBOL: "Biểu tượng",
  PHONE_NUMBER: "Số điện thoại",
  CONTACT_METHOD: "Cách liên lạc",
  ORG_ID: "Đơn vị quản lý",
  ORG_USE_ID: "Đơn vị khai thác",
  ORG_TECHNICAL_ID: "Đơn vị bảo đảm kỹ thuật",
  ORG_SUPPORT_ID: "Đơn vị hỗ trợ bảo đảm kỹ thuật",
  WARD_ID: "Mã phường/ xã",
  PARENT_ID: "Thuộc tổng trạm",
  FUNCTION_ID: "Chức năng trạm",
  AREA: "Diện tích",
  ADDRESS: "Địa chỉ trạm",
  COORDINATES: "Tọa độ",
  LONGITUDE: "Kinh độ (Độ N)",
  LATITUDE: "Vĩ độ (Độ E)",
  TYPE_ID: "Loại trạm",
  FILE_PATH: "Đường dẫn file Hồ sơ kỹ thuật trạm",
  DESC: "Mô tả",
  IS_ENABLE: "Trạng thái",
};
