version: "3"
services:
  original-gate-web:
    image: nginx:1.25-alpine-slim
    container_name: original-gate-web
    restart: always
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./web:/usr/share/nginx/html
    ports:
      - "${PUBLIC_PORT}:80"
    networks:
      - original-gate-frontend-net
    depends_on:
      - original-gate-api
      - original-gate-pgadmin

  original-gate-db:
    image: postgres:16.2-alpine3.19
    container_name: original-gate-db
    restart: always
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "PGDATA=/pgdata"
    # ports:
    #   - '127.0.0.1:${POSTGRES_PORT}:5432'
    volumes:
      - ./postgres-data:/pgdata
      - "${POSTGRES_INIT_DB_DIR}:/docker-entrypoint-initdb.d"
    networks:
      - original-gate-backend-net

  original-gate-pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: original-gate-pgadmin
    restart: always
    user: "root"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}"
      - "PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}"
    # ports:
    #   - '127.0.0.1:${PGADMIN_PORT}:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - original-gate-backend-net
      - original-gate-frontend-net
    depends_on:
      - original-gate-db

  original-gate-redis:
    image: "ghcr.io/microsoft/garnet"
    container_name: original-gate-redis
    restart: always
    # ports:
    #   - '127.0.0.1:${REDIS_PORT}:6379'
    volumes:
      - ./redis-data:/data
    networks:
      - original-gate-backend-net

  original-gate-api:
    image: directus/directus:10.10.5
    container_name: original-gate-api
    restart: always
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"
        compress: "true"
    # ports:
    #   - 8055:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
      - ./database/migrations:/directus/database-migrations
    depends_on:
      - original-gate-db
      - original-gate-redis
    env_file:
      - .env
    networks:
      - original-gate-backend-net
      - original-gate-frontend-net

networks:
  original-gate-backend-net:
  original-gate-frontend-net:
