version: "3"
services:
  original-gate-web:
    extends:
      file: docker-compose.yml
      service: original-gate-web

  original-gate-db:
    extends:
      file: docker-compose.yml
      service: original-gate-db

  original-gate-pgadmin:
    extends:
      file: docker-compose.yml
      service: original-gate-pgadmin

  original-gate-redis:
    extends:
      file: docker-compose.yml
      service: original-gate-redis

  original-gate-api:
    extends:
      file: docker-compose.yml
      service: original-gate-api

  node-app:
    build:
      context: .
      dockerfile: ./dev.Dockerfile

    container_name: original-gate-devcontainer

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - .:/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker


    # Uncomment the next four lines if you will use a ptrace-based debugger like C++, Go, and Rust.
    # cap_add:
    #   - SYS_PTRACE
    # security_opt:
    #   - seccomp:unconfined

    # Overrides default command so things don't shut down after the process ends.
    command: tail -f /dev/null
    networks:
      - original-gate-dev-net

networks:
  original-gate-dev-net:
    driver: bridge
  original-gate-backend-net:
  original-gate-frontend-net:
